import type { LearnedHeuristics } from "@/src/lib/pipeline/heuristicsBuckets";

/**
 * Snapshot of learned parameter deltas from grading corrections.
 *
 * AUTO-GENERATED by scripts/update-heuristics.mjs
 * Source: http://localhost:3000/api/corrections/learn
 * Generated at: 2026-02-12T13:16:47.588Z
 *
 * Do not edit this file by hand; instead, run:
 *   npm run learn:heuristics
 */

export const LEARNED_HEURISTICS: LearnedHeuristics | null = {
  "bandMidHue": {
    "global": {
      "meanDelta": 0.49500000000000005,
      "count": 8
    },
    "buckets": {
      "global": {
        "meanDelta": 0.49500000000000005,
        "count": 8
      },
      "exposure:unknown": {
        "meanDelta": 0.8033333333333333,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.49500000000000005,
        "count": 8
      },
      "ref_color:unknown": {
        "meanDelta": 0.49500000000000005,
        "count": 8
      },
      "exposure:under": {
        "meanDelta": 0.31,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 0.31,
        "count": 5
      }
    }
  },
  "blackRange": {
    "global": {
      "meanDelta": 0.39875,
      "count": 8
    },
    "buckets": {
      "global": {
        "meanDelta": 0.39875,
        "count": 8
      },
      "exposure:unknown": {
        "meanDelta": 0.4633333333333334,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.39875,
        "count": 8
      },
      "ref_color:unknown": {
        "meanDelta": 0.39875,
        "count": 8
      },
      "exposure:under": {
        "meanDelta": 0.36000000000000004,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 0.36000000000000004,
        "count": 5
      }
    }
  },
  "bandMidLuma": {
    "global": {
      "meanDelta": 0.13625,
      "count": 8
    },
    "buckets": {
      "global": {
        "meanDelta": 0.13625,
        "count": 8
      },
      "exposure:unknown": {
        "meanDelta": 0.11333333333333334,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.13625,
        "count": 8
      },
      "ref_color:unknown": {
        "meanDelta": 0.13625,
        "count": 8
      },
      "exposure:under": {
        "meanDelta": 0.15,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 0.15,
        "count": 5
      }
    }
  },
  "blackStrength": {
    "global": {
      "meanDelta": 5.3,
      "count": 8
    },
    "buckets": {
      "global": {
        "meanDelta": 5.3,
        "count": 8
      },
      "exposure:unknown": {
        "meanDelta": 5.3,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": 5.3,
        "count": 8
      },
      "ref_color:unknown": {
        "meanDelta": 5.3,
        "count": 8
      },
      "exposure:under": {
        "meanDelta": 5.3,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 5.3,
        "count": 5
      }
    }
  },
  "bandLowerHighHue": {
    "global": {
      "meanDelta": 0.645,
      "count": 8
    },
    "buckets": {
      "global": {
        "meanDelta": 0.645,
        "count": 8
      },
      "exposure:unknown": {
        "meanDelta": 0.15333333333333335,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.645,
        "count": 8
      },
      "ref_color:unknown": {
        "meanDelta": 0.645,
        "count": 8
      },
      "exposure:under": {
        "meanDelta": 0.9399999999999998,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 0.9399999999999998,
        "count": 5
      }
    }
  },
  "bandUpperHighHue": {
    "global": {
      "meanDelta": -0.05875000000000002,
      "count": 8
    },
    "buckets": {
      "global": {
        "meanDelta": -0.05875000000000002,
        "count": 8
      },
      "exposure:unknown": {
        "meanDelta": -0.84,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": -0.05875000000000002,
        "count": 8
      },
      "ref_color:unknown": {
        "meanDelta": -0.05875000000000002,
        "count": 8
      },
      "exposure:under": {
        "meanDelta": 0.41,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 0.41,
        "count": 5
      }
    }
  },
  "bandUpperHighSat": {
    "global": {
      "meanDelta": 0.8166666666666668,
      "count": 3
    },
    "buckets": {
      "global": {
        "meanDelta": 0.8166666666666668,
        "count": 3
      },
      "exposure:unknown": {
        "meanDelta": 0.8166666666666668,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.8166666666666668,
        "count": 3
      },
      "ref_color:unknown": {
        "meanDelta": 0.8166666666666668,
        "count": 3
      }
    }
  },
  "bandLowerHighLuma": {
    "global": {
      "meanDelta": 0.165625,
      "count": 8
    },
    "buckets": {
      "global": {
        "meanDelta": 0.165625,
        "count": 8
      },
      "exposure:unknown": {
        "meanDelta": 0.17500000000000002,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.165625,
        "count": 8
      },
      "ref_color:unknown": {
        "meanDelta": 0.165625,
        "count": 8
      },
      "exposure:under": {
        "meanDelta": 0.16,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 0.16,
        "count": 5
      }
    }
  },
  "bandUpperHighLuma": {
    "global": {
      "meanDelta": 0.07,
      "count": 3
    },
    "buckets": {
      "global": {
        "meanDelta": 0.07,
        "count": 3
      },
      "exposure:unknown": {
        "meanDelta": 0.07,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.07,
        "count": 3
      },
      "ref_color:unknown": {
        "meanDelta": 0.07,
        "count": 3
      }
    }
  },
  "bandLowerShadowHue": {
    "global": {
      "meanDelta": 0.29,
      "count": 3
    },
    "buckets": {
      "global": {
        "meanDelta": 0.29,
        "count": 3
      },
      "exposure:unknown": {
        "meanDelta": 0.29,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.29,
        "count": 3
      },
      "ref_color:unknown": {
        "meanDelta": 0.29,
        "count": 3
      }
    }
  },
  "bandUpperShadowHue": {
    "global": {
      "meanDelta": 0.31125,
      "count": 8
    },
    "buckets": {
      "global": {
        "meanDelta": 0.31125,
        "count": 8
      },
      "exposure:unknown": {
        "meanDelta": 0.3133333333333333,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.31125,
        "count": 8
      },
      "ref_color:unknown": {
        "meanDelta": 0.31125,
        "count": 8
      },
      "exposure:under": {
        "meanDelta": 0.31,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 0.31,
        "count": 5
      }
    }
  },
  "bandLowerShadowLuma": {
    "global": {
      "meanDelta": -0.17,
      "count": 8
    },
    "buckets": {
      "global": {
        "meanDelta": -0.17,
        "count": 8
      },
      "exposure:unknown": {
        "meanDelta": -0.16166666666666668,
        "count": 3
      },
      "ref_exposure:unknown": {
        "meanDelta": -0.17,
        "count": 8
      },
      "ref_color:unknown": {
        "meanDelta": -0.17,
        "count": 8
      },
      "exposure:under": {
        "meanDelta": -0.175,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": -0.175,
        "count": 5
      }
    }
  },
  "colorStrength": {
    "global": {
      "meanDelta": 0.9357142857142858,
      "count": 7
    },
    "buckets": {
      "global": {
        "meanDelta": 0.9357142857142858,
        "count": 7
      },
      "exposure:unknown": {
        "meanDelta": 0.7999999999999999,
        "count": 2
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.9357142857142858,
        "count": 7
      },
      "ref_color:unknown": {
        "meanDelta": 0.9357142857142858,
        "count": 7
      },
      "exposure:under": {
        "meanDelta": 0.99,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 0.99,
        "count": 5
      }
    }
  },
  "bandLowerHighSat": {
    "global": {
      "meanDelta": 0.3500000000000001,
      "count": 2
    },
    "buckets": {
      "global": {
        "meanDelta": 0.3500000000000001,
        "count": 2
      },
      "exposure:unknown": {
        "meanDelta": 0.3500000000000001,
        "count": 2
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.3500000000000001,
        "count": 2
      },
      "ref_color:unknown": {
        "meanDelta": 0.3500000000000001,
        "count": 2
      }
    }
  },
  "exposureStrength": {
    "global": {
      "meanDelta": 0.21999999999999997,
      "count": 2
    },
    "buckets": {
      "global": {
        "meanDelta": 0.21999999999999997,
        "count": 2
      },
      "exposure:unknown": {
        "meanDelta": 0.21999999999999997,
        "count": 2
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.21999999999999997,
        "count": 2
      },
      "ref_color:unknown": {
        "meanDelta": 0.21999999999999997,
        "count": 2
      }
    }
  },
  "bandUpperShadowLuma": {
    "global": {
      "meanDelta": -0.07142857142857142,
      "count": 7
    },
    "buckets": {
      "global": {
        "meanDelta": -0.07142857142857142,
        "count": 7
      },
      "exposure:unknown": {
        "meanDelta": -0.075,
        "count": 2
      },
      "ref_exposure:unknown": {
        "meanDelta": -0.07142857142857142,
        "count": 7
      },
      "ref_color:unknown": {
        "meanDelta": -0.07142857142857142,
        "count": 7
      },
      "exposure:under": {
        "meanDelta": -0.07,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": -0.07,
        "count": 5
      }
    }
  },
  "lumaStrength": {
    "global": {
      "meanDelta": 0.75,
      "count": 5
    },
    "buckets": {
      "global": {
        "meanDelta": 0.75,
        "count": 5
      },
      "exposure:under": {
        "meanDelta": 0.75,
        "count": 5
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.75,
        "count": 5
      },
      "ref_color:unknown": {
        "meanDelta": 0.75,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 0.75,
        "count": 5
      }
    }
  },
  "highlightFillWarmth": {
    "global": {
      "meanDelta": 0.65,
      "count": 5
    },
    "buckets": {
      "global": {
        "meanDelta": 0.65,
        "count": 5
      },
      "exposure:under": {
        "meanDelta": 0.65,
        "count": 5
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.65,
        "count": 5
      },
      "ref_color:unknown": {
        "meanDelta": 0.65,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 0.65,
        "count": 5
      }
    }
  },
  "highlightFillStrength": {
    "global": {
      "meanDelta": 0.82,
      "count": 5
    },
    "buckets": {
      "global": {
        "meanDelta": 0.82,
        "count": 5
      },
      "exposure:under": {
        "meanDelta": 0.82,
        "count": 5
      },
      "ref_exposure:unknown": {
        "meanDelta": 0.82,
        "count": 5
      },
      "ref_color:unknown": {
        "meanDelta": 0.82,
        "count": 5
      },
      "source_type:png": {
        "meanDelta": 0.82,
        "count": 5
      }
    }
  }
} as LearnedHeuristics;
